**Exploration**

In [1]:
import pandas as pd

In [2]:
tour_data = pd.read_csv('tour_player_data.csv')

In [3]:
full_data = pd.read_csv('full_df.csv')

In [4]:
tour_data

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Points,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,868,NaN,5.0,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,"1,006",1.0,3.0,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,"1,020",NaN,3.0,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,795,NaN,5.0,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,421,NaN,3.0,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2307,Carl Paulson,NaN,NaN,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$16,943"
2308,Peter Tomasulo,NaN,NaN,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$12,827"
2309,Marc Turnesa,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,159"
2310,Jesper Parnevik,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9,165"
2311,"Jim Gallagher, Jr.",NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,552"

In [7]:
full_data

,player,year,par_4_avg,par_5_avg,drive_avg,weight,DOB,height_inches,age
0,Payne Stewart,1987,3.98,4.65,269.9,NaN,NaN,0,NaN
1,Dan Pohl,1987,3.98,4.63,273.0,NaN,NaN,0,NaN
2,Lanny Wadkins,1987,3.97,4.74,253.3,NaN,NaN,0,NaN
3,Paul Azinger,1987,3.98,4.63,269.5,NaN,NaN,0,NaN
4,David Frost,1987,3.98,4.64,259.2,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...
7043,Dylan Frittelli,2023,4.11,4.66,303.1,179.0,1990-06-05,74,33.0
7044,Webb Simpson,2023,4.15,4.56,298.8,185.0,1985-08-08,74,38.0
7045,Kevin Kisner,2023,4.19,4.85,284.1,165.0,NaN,70,NaN
7046,Ryan Brehm,2023,4.12,4.71,306.6,220.0,1986-04-05,76,37.0
7047,Max McGreevy,2023,4.15,4.73,286.4,155.0,1995-05-03,71,28.0

**MVP - Target Variable**

When the average tour player distance is expected to exceed the current usda regulation?

- We have driving distance average by player
- We have average tour driving distance by year
- We have expected date of proposed rollback implementation

**Is driving distance a significant factor for scoring on a Par 4?**

**Is driving distance a significant factor for scoring on a Par 5?**

**On average, do taller players on average drive the ball further than shorter players?**

**Has the overall height of PGA Tour Players increased significantly over time?**

**Has the overall age of PGA Tour Players increased significantly over time?**

**What other pivotal technological moments in time impacted the average tour player distance?**

- Titanium -> Graphite
- Golf Ball Size Reduction

**Is driving distance the most significant factor for scoring?**

**How well do the Top drivers of the ball do compared to the average tour player?**

- Top 5 Finishes
- Top 10 Finishes
- In The Money

**How accurate are the top drivers of the ball compared to the average tour player?**